// <auto-generated />
using System;
using Foundation.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foundation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Foundation.Models.Alcohol_model", b =>
                {
                    b.Property<byte>("Alcohol_modelId")
                        .HasColumnType("tinyint")
                        .HasColumnName("alcohol_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.HasKey("Alcohol_modelId");

                    b.ToTable("Alcohol");

                    b.HasData(
                        new
                        {
                            AlcoholmodelId = (byte)1,
                            Type = "Never"
                        },
                        new
                        {
                            AlcoholmodelId = (byte)2,
                            Type = "Occasionally"
                        },
                        new
                        {
                            AlcoholmodelId = (byte)3,
                            Type = "Often"
                        },
                        new
                        {
                            AlcoholmodelId = (byte)4,
                            Type = "Daily"
                        });
                });

            modelBuilder.Entity("Foundation.Models.Business_model", b =>
                {
                    b.Property<int>("Business_modelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Business_modelId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("address");

                    b.Property<string>("Localization")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("localization");

                    b.Property<decimal>("NIP")
                        .HasMaxLength(10)
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("nip");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("name");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("postcode");

                    b.HasKey("Business_modelId");

                    b.ToTable("Business");

                    b.HasData(
                        new
                        {
                            BusinessmodelId = 1,
                            Address = "ul. Na wzgórzu 42",
                            Localization = "Rabka Zdrój",
                            NIP = 9931742334m,
                            Name = "Blachotrapez Sp. z o.o",
                            Postcode = "30-215"
                        },
                        new
                        {
                            BusinessmodelId = 2,
                            Address = "ul. Krakowska 12",
                            Localization = "Nowy Sącz",
                            NIP = 7233422312m,
                            Name = "Oknoplast Sp. z o.o.",
                            Postcode = "32-712"
                        },
                        new
                        {
                            BusinessmodelId = 3,
                            Address = "ul. Krótka 32",
                            Localization = "Warszawa",
                            NIP = 9256345423m,
                            Name = "Evenea Sp. z o.o.",
                            Postcode = "02-250"
                        },
                        new
                        {
                            BusinessmodelId = 4,
                            Address = "ul. Informatyków 1",
                            Localization = "Kraków",
                            NIP = 6722341245m,
                            Name = "Comarch S.A.",
                            Postcode = "30-230"
                        },
                        new
                        {
                            BusinessmodelId = 5,
                            Address = "ul. Rakowicka 27",
                            Localization = "Kraków",
                            NIP = 9913451273m,
                            Name = "Uniwersytet Ekonomczny w Krakowie",
                            Postcode = "30-118"
                        },
                        new
                        {
                            BusinessmodelId = 6,
                            Address = "ul. Lipowa 3",
                            Localization = "Kraków",
                            NIP = 6792933459m,
                            Name = "Neostrain Sp. z o.o.",
                            Postcode = "30-702"
                        },
                        new
                        {
                            BusinessmodelId = 7,
                            Address = "ul. Poznańska 18",
                            Localization = "Warszawa",
                            NIP = 7452342345m,
                            Name = "Polkomtel S.A.",
                            Postcode = "00-212"
                        });
                });

            modelBuilder.Entity("Foundation.Models.Men_model", b =>
                {
                    b.Property<int>("Men_modelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("men_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Men_modelId"));

                    b.Property<int>("Age")
                        .HasMaxLength(3)
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<byte>("AlcoholId")
                        .HasMaxLength(2)
                        .HasColumnType("tinyint")
                        .HasColumnName("alcohol_id");

                    b.Property<int?>("BusinessId")
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<byte>("EducationId")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint")
                        .HasColumnName("education_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("first_name");

                    b.Property<byte>("InterestFirstId")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint")
                        .HasColumnName("interest_1_id");

                    b.Property<byte>("InterestSecondId")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint")
                        .HasColumnName("interest_2_id");

                    b.Property<byte>("InterestThirdId")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint")
                        .HasColumnName("interest_3_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("last_name");

                    b.Property<string>("Localization")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("localization");

                    b.Property<string>("PetName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("pet_name");

                    b.Property<byte?>("PetTypeId")
                        .HasMaxLength(2)
                        .HasColumnType("tinyint")
                        .HasColumnName("pet_type_id");

                    b.Property<byte>("RelationshipStatusId")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint")
                        .HasColumnName("relationship_status_id");

                    b.Property<byte>("ReligionId")
                        .HasMaxLength(2)
                        .HasColumnType("tinyint")
                        .HasColumnName("religion_id");

                    b.Property<byte>("SmokingId")
                        .HasMaxLength(2)
                        .HasColumnType("tinyint")
                        .HasColumnName("smoking_id");

                    b.Property<byte>("ZodiacSignId")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint")
                        .HasColumnName("zodiac_sign_id");

                    b.HasKey("Men_modelId");

                    b.HasIndex("AlcoholId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("PetTypeId");

                    b.ToTable("Men");

                    b.HasData(
                        new
                        {
                            MenmodelId = 1,
                            Age = 20,
                            AlcoholId = (byte)1,
                            BusinessId = 2,
                            EducationId = (byte)2,
                            FirstName = "Paweł",
                            InterestFirstId = (byte)4,
                            InterestSecondId = (byte)2,
                            InterestThirdId = (byte)3,
                            LastName = "Urbański",
                            Localization = "Kraków",
                            PetName = "Dyzio",
                            PetTypeId = (byte)2,
                            RelationshipStatusId = (byte)1,
                            ReligionId = (byte)1,
                            SmokingId = (byte)1,
                            ZodiacSignId = (byte)3
                        },
                        new
                        {
                            MenmodelId = 2,
                            Age = 25,
                            AlcoholId = (byte)3,
                            BusinessId = 4,
                            EducationId = (byte)3,
                            FirstName = "Damian",
                            InterestFirstId = (byte)2,
                            InterestSecondId = (byte)1,
                            InterestThirdId = (byte)3,
                            LastName = "Jawor",
                            Localization = "Wadowice",
                            PetName = "Piorun",
                            PetTypeId = (byte)1,
                            RelationshipStatusId = (byte)1,
                            ReligionId = (byte)1,
                            SmokingId = (byte)4,
                            ZodiacSignId = (byte)1
                        },
                        new
                        {
                            MenmodelId = 3,
                            Age = 21,
                            AlcoholId = (byte)1,
                            BusinessId = 2,
                            EducationId = (byte)2,
                            FirstName = "Borys",
                            InterestFirstId = (byte)3,
                            InterestSecondId = (byte)1,
                            InterestThirdId = (byte)2,
                            LastName = "Pawlak",
                            Localization = "Toruń",
                            RelationshipStatusId = (byte)1,
                            ReligionId = (byte)1,
                            SmokingId = (byte)2,
                            ZodiacSignId = (byte)2
                        },
                        new
                        {
                            MenmodelId = 4,
                            Age = 18,
                            AlcoholId = (byte)3,
                            EducationId = (byte)1,
                            FirstName = "Kajetan",
                            InterestFirstId = (byte)2,
                            InterestSecondId = (byte)3,
                            InterestThirdId = (byte)1,
                            LastName = "Kowalski",
                            Localization = "Nowy Sącz",
                            PetName = "Saba",
                            PetTypeId = (byte)1,
                            RelationshipStatusId = (byte)3,
                            ReligionId = (byte)1,
                            SmokingId = (byte)2,
                            ZodiacSignId = (byte)1
                        },
                        new
                        {
                            MenmodelId = 5,
                            Age = 30,
                            AlcoholId = (byte)1,
                            BusinessId = 5,
                            EducationId = (byte)3,
                            FirstName = "Marcel",
                            InterestFirstId = (byte)9,
                            InterestSecondId = (byte)10,
                            InterestThirdId = (byte)5,
                            LastName = "Bąk",
                            Localization = "Warszawa",
                            PetName = "Ares",
                            PetTypeId = (byte)2,
                            RelationshipStatusId = (byte)2,
                            ReligionId = (byte)3,
                            SmokingId = (byte)2,
                            ZodiacSignId = (byte)7
                        });
                });

            modelBuilder.Entity("Foundation.Models.Pet_model", b =>
                {
                    b.Property<byte>("Pet_modelId")
                        .HasColumnType("tinyint")
                        .HasColumnName("pet_type_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.HasKey("Pet_modelId");

                    b.ToTable("Pet");

                    b.HasData(
                        new
                        {
                            PetmodelId = (byte)1,
                            Type = "Dog"
                        },
                        new
                        {
                            PetmodelId = (byte)2,
                            Type = "Cat"
                        },
                        new
                        {
                            PetmodelId = (byte)3,
                            Type = "Guinea pig"
                        });
                });

            modelBuilder.Entity("Foundation.Models.Women_model", b =>
                {
                    b.Property<int>("Women_modelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("women_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Women_modelId"));

                    b.Property<int>("Age")
                        .HasMaxLength(3)
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<byte>("AlcoholId")
                        .HasMaxLength(2)
                        .HasColumnType("tinyint")
                        .HasColumnName("alcohol_id");

                    b.Property<int?>("BusinessId")
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<byte>("EducationId")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint")
                        .HasColumnName("education_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("first_name");

                    b.Property<byte>("InterestFirstId")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint")
                        .HasColumnName("interest_1_id");

                    b.Property<byte>("InterestSecondId")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint")
                        .HasColumnName("interest_2_id");

                    b.Property<byte>("InterestThirdId")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint")
                        .HasColumnName("interest_3_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("last_name");

                    b.Property<string>("Localization")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("localization");

                    b.Property<string>("PetName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("pet_name");

                    b.Property<byte?>("PetTypeId")
                        .HasMaxLength(2)
                        .HasColumnType("tinyint")
                        .HasColumnName("pet_type_id");

                    b.Property<byte?>("Pet_modelId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RelationshipStatusId")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint")
                        .HasColumnName("relationship_status_id");

                    b.Property<byte>("ReligionId")
                        .HasMaxLength(2)
                        .HasColumnType("tinyint")
                        .HasColumnName("religion_id");

                    b.Property<byte>("SmokingId")
                        .HasMaxLength(2)
                        .HasColumnType("tinyint")
                        .HasColumnName("smoking_id");

                    b.Property<byte>("ZodiacSignId")
                        .HasMaxLength(3)
                        .HasColumnType("tinyint")
                        .HasColumnName("zodiac_sign_id");

                    b.HasKey("Women_modelId");

                    b.HasIndex("AlcoholId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("Pet_modelId");

                    b.ToTable("Women");

                    b.HasData(
                        new
                        {
                            WomenmodelId = 1,
                            Age = 20,
                            AlcoholId = (byte)1,
                            BusinessId = 2,
                            EducationId = (byte)2,
                            FirstName = "Jagoda",
                            InterestFirstId = (byte)11,
                            InterestSecondId = (byte)12,
                            InterestThirdId = (byte)13,
                            LastName = "Lis",
                            Localization = "Wadowice",
                            PetName = "Eliza",
                            PetTypeId = (byte)3,
                            RelationshipStatusId = (byte)1,
                            ReligionId = (byte)1,
                            SmokingId = (byte)2,
                            ZodiacSignId = (byte)3
                        },
                        new
                        {
                            WomenmodelId = 2,
                            Age = 27,
                            AlcoholId = (byte)3,
                            BusinessId = 4,
                            EducationId = (byte)3,
                            FirstName = "Lara",
                            InterestFirstId = (byte)2,
                            InterestSecondId = (byte)1,
                            InterestThirdId = (byte)3,
                            LastName = "Czerwik",
                            Localization = "Kraków",
                            PetName = "Beza",
                            PetTypeId = (byte)2,
                            RelationshipStatusId = (byte)1,
                            ReligionId = (byte)1,
                            SmokingId = (byte)4,
                            ZodiacSignId = (byte)1
                        },
                        new
                        {
                            WomenmodelId = 3,
                            Age = 23,
                            AlcoholId = (byte)1,
                            BusinessId = 2,
                            EducationId = (byte)2,
                            FirstName = "Wiktoria",
                            InterestFirstId = (byte)3,
                            InterestSecondId = (byte)1,
                            InterestThirdId = (byte)2,
                            LastName = "Zakrzewska",
                            Localization = "Warszawa",
                            RelationshipStatusId = (byte)1,
                            ReligionId = (byte)1,
                            SmokingId = (byte)3,
                            ZodiacSignId = (byte)2
                        },
                        new
                        {
                            WomenmodelId = 4,
                            Age = 20,
                            AlcoholId = (byte)3,
                            EducationId = (byte)1,
                            FirstName = "Helena",
                            InterestFirstId = (byte)2,
                            InterestSecondId = (byte)3,
                            InterestThirdId = (byte)1,
                            LastName = "Pikol",
                            Localization = "Nowy Sącz",
                            PetName = "Agrest",
                            PetTypeId = (byte)1,
                            RelationshipStatusId = (byte)3,
                            ReligionId = (byte)2,
                            SmokingId = (byte)2,
                            ZodiacSignId = (byte)1
                        },
                        new
                        {
                            WomenmodelId = 5,
                            Age = 32,
                            AlcoholId = (byte)3,
                            BusinessId = 1,
                            EducationId = (byte)1,
                            FirstName = "Natalia",
                            InterestFirstId = (byte)2,
                            InterestSecondId = (byte)3,
                            InterestThirdId = (byte)1,
                            LastName = "Sobczak",
                            Localization = "Sandomierz",
                            PetName = "Fafik",
                            PetTypeId = (byte)1,
                            RelationshipStatusId = (byte)3,
                            ReligionId = (byte)2,
                            SmokingId = (byte)2,
                            ZodiacSignId = (byte)1
                        });
                });

            modelBuilder.Entity("Foundation.Models.Men_model", b =>
                {
                    b.HasOne("Foundation.Models.Alcohol_model", "Alcohol_model")
                        .WithMany("Men_model")
                        .HasForeignKey("AlcoholId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foundation.Models.Business_model", "Business_model")
                        .WithMany("Men_model")
                        .HasForeignKey("BusinessId");

                    b.HasOne("Foundation.Models.Pet_model", "Pet_model")
                        .WithMany("Men_model")
                        .HasForeignKey("PetTypeId");

                    b.Navigation("Alcohol_model");

                    b.Navigation("Business_model");

                    b.Navigation("Pet_model");
                });

            modelBuilder.Entity("Foundation.Models.Women_model", b =>
                {
                    b.HasOne("Foundation.Models.Alcohol_model", "Alcohol_model")
                        .WithMany("Women_model")
                        .HasForeignKey("AlcoholId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foundation.Models.Business_model", "Business_model")
                        .WithMany("Women_model")
                        .HasForeignKey("BusinessId");

                    b.HasOne("Foundation.Models.Pet_model", null)
                        .WithMany("Women_model")
                        .HasForeignKey("Pet_modelId");

                    b.Navigation("Alcohol_model");

                    b.Navigation("Business_model");
                });

            modelBuilder.Entity("Foundation.Models.Alcohol_model", b =>
                {
                    b.Navigation("Men_model");

                    b.Navigation("Women_model");
                });

            modelBuilder.Entity("Foundation.Models.Business_model", b =>
                {
                    b.Navigation("Men_model");

                    b.Navigation("Women_model");
                });

            modelBuilder.Entity("Foundation.Models.Pet_model", b =>
                {
                    b.Navigation("Men_model");

                    b.Navigation("Women_model");
                });
#pragma warning restore 612, 618
        }
    }
}
